from django.urls import path
from . import views

urlpatterns = [
    path('createcasesheet/', views.createcasesheet, name="createcasesheet"),
    path('casesheet_saved/', views.casesheet_saved, name="casesheet_saved"),
    path('question1/', views.question1, name="question1"),
    path('question2/', views.question2, name="question2"),
    path('question3/', views.question3, name="question3"),
    path('question4/', views.question4, name="question4"),
    path('question5/', views.question5, name="question5"),
    path('question6/', views.question6, name="question6"),
    path('question7/', views.question7, name="question7"),
    path('question8/', views.question8, name="question8"),
    path('question9/', views.question9, name="question9"),
    path('question10/', views.question10, name="question10"),
    path('question11/', views.question11, name="question11"),
    path('question12/', views.question12, name="question12"),
    path('question13/', views.question13, name="question13"),
    path('question14/', views.question14, name="question14"),
    path('question15/', views.question15, name="question15"),
    path('question16/', views.question16, name="question16"),
    path('question17/', views.question17, name="question17"),
    path('question18/', views.question18, name="question18"),
    path('question19/', views.question19, name="question19"),
    path('question20/', views.question20, name="question20"),
    path('question21/', views.question21, name="question21"),
    path('question22/', views.question22, name="question22"),
    path('question23/', views.question23, name="question23"),
    path('question24/', views.question24, name="question24"),
    path('question25/', views.question25, name="question25"),
    path('question26/', views.question26, name="question26"),
    path('question27/', views.question27, name="question27"),
    path('question28/', views.question28, name="question28"),
    path('question29/', views.question29, name="question29"),
    path('question30/', views.question30, name="question30"),
    path('question31/', views.question31, name="question31"),
    path('question32/', views.question32, name="question32"),
    path('question33/', views.question33, name="question33"),
    path('question34/', views.question34, name="question34"),
    path('question35/', views.question35, name="question35"),
    path('sub_rubric_handler_q4/', views.sub_rubric_handler_q4,
         name="sub_rubric_handler_q4"),
    path('sub_rubric_handler_q5/', views.sub_rubric_handler_q5,
         name="sub_rubric_handler_q5"),
    path('sub_rubric_handler_q6/', views.sub_rubric_handler_q6,
         name="sub_rubric_handler_q6"),
    path('sub_rubric_handler_q7/', views.sub_rubric_handler_q7,
         name="sub_rubric_handler_q7"),
    path('sub_rubric_handler_q8/', views.sub_rubric_handler_q8,
         name="sub_rubric_handler_q8"),
    path('sub_rubric_handler_q9/', views.sub_rubric_handler_q9,
         name="sub_rubric_handler_q9"),
    path('sub_rubric_handler_q10/', views.sub_rubric_handler_q10,
         name="sub_rubric_handler_q10"),
    path('sub_rubric_handler_q11/', views.sub_rubric_handler_q11,
         name="sub_rubric_handler_q11"),
    path('sub_rubric_handler_q12/', views.sub_rubric_handler_q12,
         name="sub_rubric_handler_q12"),
    path('sub_rubric_handler_q13/', views.sub_rubric_handler_q13,
         name="sub_rubric_handler_q13"),
    path('sub_rubric_handler_q14/', views.sub_rubric_handler_q14,
         name="sub_rubric_handler_q14"),
    path('sub_rubric_handler_q15/', views.sub_rubric_handler_q15,
         name="sub_rubric_handler_q15"),
    path('sub_rubric_handler_q16/', views.sub_rubric_handler_q16,
         name="sub_rubric_handler_q16"),
    path('sub_rubric_handler_q17/', views.sub_rubric_handler_q17,
         name="sub_rubric_handler_q17"),
    path('sub_rubric_handler_q18/', views.sub_rubric_handler_q18,
         name="sub_rubric_handler_q18"),
    path('sub_rubric_handler_q19/', views.sub_rubric_handler_q19,
         name="sub_rubric_handler_q19"),
    path('sub_rubric_handler_q20/', views.sub_rubric_handler_q20,
         name="sub_rubric_handler_q20"),
    path('sub_rubric_handler_q21/', views.sub_rubric_handler_q21,
         name="sub_rubric_handler_q21"),
    path('sub_rubric_handler_q22/', views.sub_rubric_handler_q22,
         name="sub_rubric_handler_q22"),
    path('sub_rubric_handler_q23/', views.sub_rubric_handler_q23,
         name="sub_rubric_handler_q23"),
    path('sub_rubric_handler_q24/', views.sub_rubric_handler_q24,
         name="sub_rubric_handler_q24"),
    path('sub_rubric_handler_q25/', views.sub_rubric_handler_q25,
         name="sub_rubric_handler_q25"),
    path('sub_rubric_handler_q26/', views.sub_rubric_handler_q26,
         name="sub_rubric_handler_q26"),
    path('sub_rubric_handler_q27/', views.sub_rubric_handler_q27,
         name="sub_rubric_handler_q27"),
    path('sub_rubric_handler_q28/', views.sub_rubric_handler_q28,
         name="sub_rubric_handler_q28"),
    path('sub_rubric_handler_q29/', views.sub_rubric_handler_q29,
         name="sub_rubric_handler_q29"),
    path('sub_rubric_handler_q30/', views.sub_rubric_handler_q30,
         name="sub_rubric_handler_q30"),
    path('sub_rubric_handler_q31/', views.sub_rubric_handler_q31,
         name="sub_rubric_handler_q31"),
    path('sub_rubric_handler_q32/', views.sub_rubric_handler_q32,
         name="sub_rubric_handler_q32"),
    path('sub_rubric_handler_q33/', views.sub_rubric_handler_q33,
         name="sub_rubric_handler_q33"),
    path('sub_rubric_handler_q34/', views.sub_rubric_handler_q34,
         name="sub_rubric_handler_q34"),
    path('sub_rubric_handler_q35/', views.sub_rubric_handler_q35,
         name="sub_rubric_handler_q35"),
    path('display_casesheet/', views.display_casesheet, name="display_casesheet"),
    path('pdf_view/<int:id>', views.pdf_view, name="pdf_view"),
    path('pdf_download/<int:id>', views.pdf_download, name="pdf_download"),
    # path('display_casesheet_pdf/', views.display_casesheet_pdf, name="display_casesheet_pdf"),
    path('edit_casesheet/<int:pk>', views.edit_casesheet, name="edit_casesheet")
]
