# Generated by Django 4.1.1 on 2022-09-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_medical_narcotics_sports_history_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_medical_history',
            name='age',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='patient_medical_history',
            name='marital_status',
            field=models.BooleanField(default=False),
        ),
    ]
