# Generated by Django 4.1.1 on 2022-09-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_patient_medical_history_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_medical_history',
            name='age',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='patient_medical_history',
            name='marital_status',
            field=models.BooleanField(),
        ),
    ]
