# Generated by Django 4.1.1 on 2022-09-14 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_medical_narcotics_sports_history_sports_bool_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medical_narcotics_sports_history',
            old_name='medical_history_asthama',
            new_name='medical_history_asthma',
        ),
    ]
