# Generated by Django 4.1.1 on 2022-09-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_medical_history_asthama_medical_narcotics_sports_history_medical_history_asthma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_medical_history',
            name='age',
        ),
        migrations.AlterField(
            model_name='medical_narcotics_sports_history',
            name='sports_name',
            field=models.CharField(default='None', max_length=40),
        ),
    ]
