# Generated by Django 3.2.7 on 2022-09-23 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0007_remove_patient_medical_history_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('specialization', models.CharField(default='None', max_length=20)),
                ('Qualification', models.CharField(default='MBBS', max_length=20)),
                ('hospitalname', models.CharField(default='Bharati Vidyapeeth Homeopathy Hospital', max_length=100)),
            ],
        ),
    ]
