# Generated by Django 4.1.1 on 2022-11-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_doctor_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_profile',
            name='Qualification',
            field=models.CharField(default='BHMRC', max_length=20),
        ),
    ]
