# Generated by Django 4.1.1 on 2022-11-03 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_Case_Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_sheet_name', models.CharField(default='MyCaseSheet', max_length=50)),
                ('majorlocation', models.CharField(max_length=20, null=True)),
                ('minorlocation', models.CharField(max_length=50, null=True)),
                ('problem', models.CharField(max_length=30, null=True)),
                ('q4', models.CharField(max_length=1000, null=True)),
                ('q5', models.CharField(max_length=1000, null=True)),
                ('q6', models.CharField(max_length=1000, null=True)),
                ('q7', models.CharField(max_length=1000, null=True)),
                ('q8', models.CharField(max_length=1000, null=True)),
                ('q9', models.CharField(max_length=1000, null=True)),
                ('q10', models.CharField(max_length=1000, null=True)),
                ('q11', models.CharField(max_length=1000, null=True)),
                ('q12', models.CharField(max_length=1000, null=True)),
                ('q13', models.CharField(max_length=1000, null=True)),
                ('q14', models.CharField(max_length=1000, null=True)),
                ('q15', models.CharField(max_length=1000, null=True)),
                ('q16', models.CharField(max_length=1000, null=True)),
                ('q17', models.CharField(max_length=1000, null=True)),
                ('q18', models.CharField(max_length=1000, null=True)),
                ('q19', models.CharField(max_length=1000, null=True)),
                ('q20', models.CharField(max_length=1000, null=True)),
                ('q21', models.CharField(max_length=1000, null=True)),
                ('q22', models.CharField(max_length=1000, null=True)),
                ('q23', models.CharField(max_length=1000, null=True)),
                ('q24', models.CharField(max_length=1000, null=True)),
                ('q25', models.CharField(max_length=1000, null=True)),
                ('all_medicine_scores', jsonfield.fields.JSONField()),
                ('top_medicine_scores', jsonfield.fields.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
