# Generated by Django 3.2.7 on 2023-02-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_case_sheet',
            name='question1',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='question10',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='question11',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='question12',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='question13',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='question14',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='question15',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='question16',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='question17',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='question18',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='question19',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='question2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='question20',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='question21',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='question22',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='question23',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='question24',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='question25',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='question3',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='question4',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='question5',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='question6',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='question7',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='question8',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='question9',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
