# Generated by Django 3.2.7 on 2023-03-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230203_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_case_sheet',
            name='q26',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='q27',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='q28',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='q29',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='q30',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='q31',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='q32',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='q33',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='q34',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='q35',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='question26',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='question27',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='question28',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='question29',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='question30',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='question31',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='question32',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='question33',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='question34',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patient_case_sheet',
            name='question35',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
